apiVersion: apps/v1
kind: Deployment
metadata:
  name: arq-worker
  namespace: car-recognition

spec:
  replicas: 1
  selector:
    matchLabels:
      app: arq-worker

  template:
    metadata:
      labels:
        app: arq-worker

    spec:
      containers:
        - name: arq-worker
          image: car-recognition-system:latest
          imagePullPolicy: IfNotPresent

          command:
            - arq
            - app.arq_worker.WorkerSettings

          envFrom:
            - secretRef:
                name: car-recognition-secret

          env:
            - name: S3_ENDPOINT_URL
              value: http://minio:9000