apiVersion: v1
kind: ConfigMap
metadata:
  name: car-recognition-config
  namespace: car-recognition

data:
  DATABASE_HOST: postgres
  DATABASE_NAME: car_recognition

  REDIS_HOST: redis

  S3_ENDPOINT_URL: http://minio:9000
  S3_BUCKET_NAME: car-images