apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskiq-worker
  namespace: car-recognition

spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskiq-worker

  template:
    metadata:
      labels:
        app: taskiq-worker

    spec:
      containers:
        - name: taskiq-worker
          image: car-recognition-system:latest
          imagePullPolicy: IfNotPresent

          command:
            - taskiq
            - worker
            - app.taskiq_tasks:broker

          envFrom:
            - secretRef:
                name: car-recognition-secret

          env:
            - name: S3_ENDPOINT_URL
              value: http://minio:9000